/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TodoApp {}
  interface TodoAppAttributes extends StencilHTMLAttributes {}

  interface YourTodo {}
  interface YourTodoAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'TodoApp': Components.TodoApp;
    'YourTodo': Components.YourTodo;
  }

  interface StencilIntrinsicElements {
    'todo-app': Components.TodoAppAttributes;
    'your-todo': Components.YourTodoAttributes;
  }


  interface HTMLTodoAppElement extends Components.TodoApp, HTMLStencilElement {}
  var HTMLTodoAppElement: {
    prototype: HTMLTodoAppElement;
    new (): HTMLTodoAppElement;
  };

  interface HTMLYourTodoElement extends Components.YourTodo, HTMLStencilElement {}
  var HTMLYourTodoElement: {
    prototype: HTMLYourTodoElement;
    new (): HTMLYourTodoElement;
  };

  interface HTMLElementTagNameMap {
    'todo-app': HTMLTodoAppElement
    'your-todo': HTMLYourTodoElement
  }

  interface ElementTagNameMap {
    'todo-app': HTMLTodoAppElement;
    'your-todo': HTMLYourTodoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
